spring:
  profiles: 
    active: dev
    
  batch:
    job:
      enabled: false  
      names: ${job.name:NONE}
  datasource:  
    hikari::
      jdbc-url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      username: user1
      password: passw0rd!
      driver-class-name: com.mysql.cj.jdbc.Driver
