version: '2'

networks:
  database:

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
     - database
    ports:
     - 3096:3306
    volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=passw0rd!
     - MYSQL_USER=user1
     - MYSQL_PASSWORD=passw0rd!
     - MYSQL_DATABASE=demo
     - TZ=Asia/Seoul
    user: 1000:100

